export const SESSION_SET = 'SESSION_SET';

export const SIGN_IN = 'SIGN_IN';
export const SIGN_UP = 'SIGN_UP';
export const TROUBLE_SIGNING_IN = 'TROUBLE_SIGNING_IN';

export const VEHICLE_LIST = 'VEHICLE_LIST';
export const VEHICLE = 'VEHICLE';
export const VEHICLE_CREATE = 'VEHICLE_CREATE';
export const VEHICLE_UPDATE = 'VEHICLE_UPDATE';
export const VEHICLE_DELETE = 'VEHICLE_DELETE';

export const ACCOUNT = 'ACCOUNT';
export const ACCOUNT_UPDATE = 'ACCOUNT_UPDATE';
export const ACCOUNT_DELETE = 'ACCOUNT_DELETE';

export const BROADCAST_CREATE = 'BROADCAST_CREATE';
export const BROADCAST_DELETE = 'BROADCAST_DELETE';
